spring.application.name=financred
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.transaction.default-timeout=30

server.port=${SERVER_PORT}
spring.security.user.name=admin
spring.security.user.password=admin

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO

logging.level.org.springframework=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.web=INFO

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=INFO

spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.web.request.auto-time-requests=true
management.metrics.enable.all=true

app.jwtSecret=${JWTSECRET}

spring.profiles.active=prod

logging.level.org.springframework.security.web.FilterChainProxy=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web.servlet=INFO
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate=INFO