spring.jpa.properties.hibernate.default_schema=financred
spring.datasource.url=jdbc:postgresql://localhost:5432/financred
spring.datasource.username=api_backend_financred
spring.datasource.password=uUrogTjQXcJHEbVNu
spring.jpa.hibernate.ddl-auto=none
spring.transaction.default-timeout=30
server.port=8080
spring.security.usuario.name=admin
spring.security.usuario.password=admin
app.jwtSecret=my-secret-key-from-back-end-financred-tec
logging.level.org.springframework.security=INFO
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO
logging.level.org.springframework.web.servlet=INFO
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate=INFO
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123